export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const SET_INGREDIENTS = 'SET_INGREDIENS';
export const FETC_INGREDIENTS_FAILED = 'FETCH_INGREDIENTS_FAILED';
